version: "3"
services:
  host:
    build: ./host
    env_file: ./host/.env
    ports:
      - 8080:8080
  order-ms:
    build: ./order-ms
    env_file: ./order-ms/.env
    ports:
      - 8081:8081
  products-ms:
    build: ./products-ms
    env_file: ./products-ms/.env
    ports:
      - 8082:8082
